### ISSUE TITLE
Ubuntu 18 support?

### ISSUE THREAD

**Issue by dav3** [olegzhr/altprobe#2]
Would it be possible to update altprobe to compile on an Ubuntu 18 install?  While it compiles fine in Ubuntu 16.04 LTS, that release becomes End of Life on April 30, 2021.

When I try to compile on Ubuntu 18.04.5 LTS, I get the following error:
```
user@device:~/src/altprobe/src$ make
"make" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
make[1]: Entering directory '/home/decoster/src/altprobe/src'
"make"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-Linux/collector
make[2]: Entering directory '/home/decoster/src/altprobe/src'
mkdir -p build/Debug/GNU-Linux
rm -f "build/Debug/GNU-Linux/aggalerts.o.d"
g++ -I/usr/include/ -I/usr/include/boost -I/usr/local/include/hiredis -I/usr/local/include/activemq-cpp-3.9.5/ -I/usr/include/apr-1.0/ -DBIG_JOINS=1 -D_REENTERANT -g -Wno-write-strings -fno-strict-aliasing -pthread -std=gnu++11 -Wno-deprecated   -c -g -MMD -MP -MF "build/Debug/GNU-Linux/aggalerts.o.d" -o build/Debug/GNU-Linux/aggalerts.o aggalerts.cpp
In file included from sinks.h:12:0,
                 from source.h:13,
                 from aggalerts.h:15,
                 from aggalerts.cpp:8:
loclog.h:32:5: error: reference to âofstreamâ is ambiguous
         ofstream ostream;
         ^~~~~~~~
In file included from /usr/include/boost/filesystem/string_file.hpp:14:0,
                 from /usr/include/boost/filesystem.hpp:19,
                 from loclog.h:13,
                 from sinks.h:12,
                 from source.h:13,
                 from aggalerts.h:15,
                 from aggalerts.cpp:8:
/usr/include/boost/filesystem/fstream.hpp:170:32: note: candidates are: typedef class boost::filesystem::basic_ofstream<char> boost::filesystem::ofstream
   typedef basic_ofstream<char> ofstream;
                                ^~~~~~~~
In file included from /usr/include/c++/7/memory:72:0,
                 from /usr/include/boost/lockfree/spsc_queue.hpp:14,
                 from main.h:38,
                 from ids.h:11,
                 from aggalerts.h:13,
                 from aggalerts.cpp:8:
/usr/include/c++/7/iosfwd:165:34: note:                 typedef class std::basic_ofstream<char> std::ofstream
   typedef basic_ofstream<char>   ofstream;
                                  ^~~~~~~~
nbproject/Makefile-Debug.mk:86: recipe for target 'build/Debug/GNU-Linux/aggalerts.o' failed
make[2]: *** [build/Debug/GNU-Linux/aggalerts.o] Error 1
make[2]: Leaving directory '/home/decoster/src/altprobe/src'
nbproject/Makefile-Debug.mk:79: recipe for target '.build-conf' failed
make[1]: *** [.build-conf] Error 2
make[1]: Leaving directory '/home/decoster/src/altprobe/src'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
make: *** [.build-impl] Error 2
```

**Comment by olegzhr** [comment]
Hi, I'm planning to update of Altprobe for supporting Ubuntu 18. Think, in this October.

**Comment by olegzhr** [comment]
Hi, altprobe was updated to support installation in Ubuntu 18.

**Comment by olegzhr** [comment]
Altprobe was updated to compile on an Ubuntu 18 install
